version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: npm
    schedule:
      interval: weekly
    versioning-strategy: increase
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    schedule:
      interval: weekly
